name: Build and publish to PyPI 
description: Build the CAS client and deploy it to PyPI
inputs:
  python-version:
    required: true
    description: "Python version to build the package with"
    default: "3.11"
  pypi-type:
    required: true
    description: "The type of PyPI deployment to perform: test or prod"
runs:
  using: "composite"
  steps:
    - name: Verify git environment
      run: |
        if [ "${{ github.ref_type }}" == "tag" ]; then
          echo "Building and publishing package for tag ${{ github.ref }}."
        else
          echo "::error::This action can only be run on a tag."
          exit 1
        fi
      shell: bash

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install build
      shell: bash

    - name: Build Package
      run: python -m build
      shell: bash

    - name: Publish Package Distributions to Appropriate PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.pypi-type == 'test' && 'https://test.pypi.org/legacy/' || '' }}
    