_API_BASE_ENDPOINT = "api"
_API_CELL_OPERATIONS_ENDPOINT_PREFIX = f"{_API_BASE_ENDPOINT}/cellarium-cell-operations"
_API_GENERAL_ENDPOINT_PREFIX = f"{_API_BASE_ENDPOINT}/cellarium-general"
# General
VALIDATE_TOKEN = f"{_API_GENERAL_ENDPOINT_PREFIX}/validate-token"
APPLICATION_INFO = f"{_API_GENERAL_ENDPOINT_PREFIX}/application-info"
GET_FEATURE_SCHEMAS = f"{_API_GENERAL_ENDPOINT_PREFIX}/feature-schemas"
GET_SCHEMA_BY_NAME = f"{_API_GENERAL_ENDPOINT_PREFIX}/feature-schema/{{schema_name}}"
LIST_MODELS = f"{_API_GENERAL_ENDPOINT_PREFIX}/list-models"
# Cell Analysis
ANNOTATE = f"{_API_CELL_OPERATIONS_ENDPOINT_PREFIX}/annotate"
NEAREST_NEIGHBOR_SEARCH = f"{_API_CELL_OPERATIONS_ENDPOINT_PREFIX}/nearest-neighbor-search"
QUERY_CELLS_BY_IDS = f"{_API_CELL_OPERATIONS_ENDPOINT_PREFIX}/query-cells-by-ids"
