name: Build & Publish CAS

on:
  workflow_dispatch:
    inputs:
      pypi-type:
        description: "Target index"
        required: true
        default: "test"
        type: choice
        options: [test, prod]

jobs:
  publish-to-pypi:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ inputs.pypi-type == 'prod' && 'pypi' || 'test-pypi' }}
      url:  ${{ inputs.pypi-type == 'prod'
                 && 'https://pypi.org/p/cellarium-cas'
                 || 'https://test.pypi.org/p/cellarium-cas' }}

    steps:
      - name: Verify git environment
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "Building and publishing package for tag ${{ github.ref }}."
          else
            echo "::error::This action can only be run on a tag."
            exit 1
          fi
        shell: bash

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build dists (sdist + wheel)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/base.txt build
          python -m build

      - name: Publish to selected index (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ inputs.pypi-type == 'test' && 'https://test.pypi.org/legacy/' || '' }}
